spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/cricketdb?createDatabaseIfNotExist=true
    username: root
    password: root123
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: cricket-app

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
